CREATE TABLE cliente
( 
id_clie serial NOT NULL, 
clie_nome char(120), 
clie_cpf char(20), 
clie_cep char(10), 
clie_cidade char(40), 
clie_uf char(2), 
clie_pais char(3), 
clie_endereco char(80), 
clie_numero char(20), 
clie_complemento char(40), 
clie_senha char(30), 
clie_mailer int4 DEFAULT 0, 
clie_entrega_cep char(10), 
clie_entrega_cidade char(40), 
clie_entrega_uf char(2), 
clie_entrega_endereco char(80), 
clie_entrega_numero char(20), 
clie_entrega_complemento char(40), 
clie_tipo char(1) DEFAULT 'N', 
clie_login char(15), 
clie_email char(100), 
clie_fone_ddd char(8), 
clie_fone_numero char(12), 
clie_fone_fax char(12), 
clie_fone_celular char(12), 
clie_codigo char(7), 
clie_entrega_bairro char(25), 
clie_bairro char(25), 
clie_entrega_mesmo char(1) 
)